### ISSUE TITLE
dead links

### ISSUE THREAD

**Issue by viktorahlstrom** [agelber/allthe2048#154]
"11" (http://t2.technion.ac.il/~s7395779/)
"2048 - A Mostly Wrong History of Programming Languages" (http://duarteduarte.tk/2048/)
"1 048 576" (http://eway0.com/2048/)
"2048 in French" (http://2048.wiity.net)

**Comment by viktorahlstrom** [comment]
"2048 - A Mostly Wrong History of Programming Languages" (http://duarteduarte.tk/2048/) is broken.

**Comment by viktorahlstrom** [comment]
"1 048 576" (http://eway0.com/2048/) is broken.

**Comment by viktorahlstrom** [comment]
"2048 in French" (http://2048.wiity.net) is broken.

**Comment by agelber** [comment]
Thank you very much! :beers: 
080d787ed3156652b6814101520933c5b963b935
